name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [ CI_MD-CSS-JS ]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [ CI_MD-CSS-JS ]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_LOG: Reports 
          DEFAULT_BRANCH: CI_MD-CSS-JS
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: true
          LOG_FILE: super-linter.txt 
      
      - name: Rename and Move
        if: always()
        run: | 
         if [ ! -d LOG ]; then 
          mkdir LOG; mv super-linter.log super-linter.txt; mv super-linter.txt LOG; 
         fi
      
      - uses: EndBug/add-and-commit@v9.1.1
        if: always()
        with: 
         add: LOG/super-linter.txt
