name: 'HTML Validator'
on:
 push:
   branches: [ CI_HTML_Valdation ]
 pull_request:
   branches: [ main ]
  
jobs: 
  build:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      
      with:
        root: ./
        format: text
        blacklist: invalid
      
    - name: Rename and Move
      if: always()
      run: if [ ! -d "logStorage" ]; then mkdir logStorage; mv log.log HTML_Logs.txt; mv HTML_Logs.txt logStorage
      
    - uses: EndBug/add-and-commit@v9.1.1
      if: always()
      with: 
        add: logStorage/HTML_Logs.txt
